export const technologies = [
  {
    order: 10,
    name: "ASP.NET",
    logo: "aspnet.png",
    info: "Robust backend servers",
    url: "https://dotnet.microsoft.com/apps/aspnet",
    important: true,
  },
  {
    order: 10,
    name: "Amazon AWS",
    logo: "aws.png",
    info: "Cloud hosting, distribution, services",
    url: "https://aws.amazon.com/",
  },
  {
    order: 10,
    name: "C#",
    logo: "cs.svg",
    info: "Powerful statically typed programming language",
    url: "https://docs.microsoft.com/en-us/dotnet/csharp/",
    important: true,
  },
  {
    order: 1,
    name: "CSS3",
    logo: "css.png",
    info: "Control the way elements are displayed in the web browser",
    url: "https://en.wikipedia.org/wiki/Cascading_Style_Sheets",
    level: 1,
    important: true,
  },
  {
    order: 10,
    name: "Docker",
    logo: "docker.png",
    info: "Package servers in reusable, distributable, reliable containers",
    url: "https://www.docker.com/",
  },
  {
    order: 10,
    name: "ExpressJS",
    logo: "express.jpeg",
    info: "Lightweight but powerful NodeJS-based backend server",
    url: "https://expressjs.com/",
    level: 2,
  },
  {
    order: 10,
    name: "Figma",
    logo: "figma.svg",
    info: "Design and share interactive web and mobile mockups",
    url: "https://www.figma.com/",
  },
  {
    order: 2,
    name: "Heroku",
    logo: "heroku.png",
    info: "Cloud-based web hosting platform",
    url: "https://www.heroku.com/",
    level: 2,
  },
  {
    order: 0,
    name: "HTML5",
    logo: "html.png",
    info: "Structure web pages and components",
    url: "https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5",
    level: 1,
    important: true,
  },
  {
    order: 10,
    name: "Jest",
    logo: "jest.png",
    info: "Test javascript code and web components",
    url: "https://jestjs.io/",
    level: 3,
  },
  {
    order: 1,
    name: "JavaScript",
    logo: "js.png",
    info: "",
    url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    level: 1,
    important: true,
  },
  {
    order: 10,
    name: "Mongo DB",
    logo: "mongo.png",
    info: "",
    url: "https://www.mongodb.com/",
    important: true,
  },
  {
    order: 3,
    name: "NodeJS",
    logo: "node.webp",
    info: "",
    url: "https://nodejs.org/",
    level: 4,
    important: true,
  },
  {
    order: 2,
    name: "NPM - Node Package Manager",
    logo: "npm.png",
    info: "",
    url: "https://www.npmjs.com/",
  },
  {
    order: 10,
    name: "PostgrSQL",
    logo: "pg.png",
    info: "",
    url: "https://www.postgresql.org/",
    important: true,
  },
  {
    order: 10,
    name: "ReactJS",
    logo: "react.png",
    info: "",
    url: "https://reactjs.org/",
    important: true,
  },
  {
    order: 10,
    name: "SASS",
    logo: "sass.svg",
    info: "",
    url: "https://sass-lang.com/",
  },
  {
    order: 10,
    name: "TypeScript",
    logo: "tsd.png",
    info: "",
    url: "https://www.typescriptlang.org/",
    important: true,
  },
  {
    order: 10,
    name: "Visual Studio Code",
    logo: "vscode.png",
    info: "",
    url: "https://code.visualstudio.com/",
    level: 1,
  },
  {
    order: 10,
    name: "VueJS",
    logo: "vue.png",
    info: "",
    url: "https://vuejs.org/",
    important: true,
  },
  {
    order: 10,
    name: "Chrome",
    logo: "chrome.png",
    info: "",
    url: "https://www.google.com/chrome/",
    level: 1,
  },
  {
    order: 10,
    name: "Github",
    logo: "github.svg",
    info: "",
    url: "https://github.com",
    level: 1,
    important: true,
  },
  {
    order: 10,
    name: "Postman",
    logo: "postman.png",
    info: "",
    url: "https://postman.com",
  },
  {
    order: 10,
    name: "Terminal",
    logo: "terminal.png",
    info: "",
    url: "http://linuxcommand.org/",
    level: 1,
  },
];
