const SUPPORTED_LANGS = "something";
const SUPPORTED_SUBMIT_TYPES = "something";
const BILLING_ADDRESS_COLLECTION_TYPES = "something";
const STRIPE_PK_LIVE = "something";
const STRIPE_PK_TEST = "something";

export {
  SUPPORTED_LANGS,
  SUPPORTED_SUBMIT_TYPES,
  BILLING_ADDRESS_COLLECTION_TYPES,
  STRIPE_PK_LIVE,
  STRIPE_PK_TEST,
};
