name: CICD
on: push
jobs:

#    ______            __  _                              
#   / ____/___  ____  / /_(_)___  __  ______  __  _______ 
#  / /   / __ \/ __ \/ __/ / __ \/ / / / __ \/ / / / ___/ 
# / /___/ /_/ / / / / /_/ / / / / /_/ / /_/ / /_/ (__  )  
# \____/\____/_/_/_/\__/_/_/ /_/\__,_/\____/\__,_/____/   
#    /  _/___  / /____  ____ __________ _/ /_(_)___  ____ 
#    / // __ \/ __/ _ \/ __ `/ ___/ __ `/ __/ / __ \/ __ \
#  _/ // / / / /_/  __/ /_/ / /  / /_/ / /_/ / /_/ / / / /
# /___/_/ /_/\__/\___/\__, /_/   \__,_/\__/_/\____/_/ /_/ 
#                    /____/                               

  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v1
    
      - name: Setup Node
        uses: actions/setup-node@v1
        with: 
          node-version: 13.x
      
      - name: Install Dependencies
        run: npm i

      - name: Build the code
        run: npm run build

      