name: Continuous Delivery
on:
  push:
    branches:
      - master
  pull_request:


#    _____            _   _                               
#   / ____|          | | (_)                              
#  | |     ___  _ __ | |_ _ _ __  _   _  ___  _   _ ___   
#  | |    / _ \| '_ \| __| | '_ \| | | |/ _ \| | | / __|  
#  | |___| (_) | | | | |_| | | | | |_| | (_) | |_| \__ \  
#   \_____\___/|_| |_|\__|_|_| |_|\__,_|\___/ \__,_|___/  
#  |_   _|     | |                     | | (_)            
#    | |  _ __ | |_ ___  __ _ _ __ __ _| |_ _  ___  _ __  
#    | | | '_ \| __/ _ \/ _` | '__/ _` | __| |/ _ \| '_ \ 
#   _| |_| | | | ||  __/ (_| | | | (_| | |_| | (_) | | | |
#  |_____|_| |_|\__\___|\__, |_|  \__,_|\__|_|\___/|_| |_|
#                        __/ |                            
#                       |___/                             

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Node Modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-cache

      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Install Deps
        run: npm i

      - name: Build
        run: npm run build

      - name: Store Artifact 
        uses: actions/upload-artifact@v2
        with:
          name: website-dist
          path: dist

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-cache

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm i

      - name: Lint the code
        run: echo simulating lint #npm run lint

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-cache

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm i

      - name: Run Unit Tests
        run: npm t

  security-audit:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Check for security issue
        run: echo simulating audit #npm audit --audit-level=critical #or "high"

  static-analysis:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v1
  
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript
  
      - name: Perform Analysis
        #uses: github/codeql-action/analyze@v1
        run: echo Simulating static analysis


#    _____            _   _                                  
#   / ____|          | | (_)                                 
#  | |     ___  _ __ | |_ _ _ __  _   _  ___  _   _ ___      
#  | |    / _ \| '_ \| __| | '_ \| | | |/ _ \| | | / __|     
#  | |___| (_) | | | | |_| | | | | |_| | (_) | |_| \__ \     
#   \_____\___/|_| |_|\__|_|_| |_|\__,_|\___/ \__,_|___/ _   
#  |  __ \           | |                                | |  
#  | |  | | ___ _ __ | | ___  _   _ _ __ ___   ___ _ __ | |_ 
#  | |  | |/ _ \ '_ \| |/ _ \| | | | '_ ` _ \ / _ \ '_ \| __|
#  | |__| |  __/ |_) | | (_) | |_| | | | | | |  __/ | | | |_ 
#  |_____/ \___| .__/|_|\___/ \__, |_| |_| |_|\___|_| |_|\__|
#              | |             __/ |                         
#              |_|            |___/                          

  deploy-prod:
    runs-on: ubuntu-latest
    needs: [build, test, lint, security-audit, static-analysis]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Retrieve Artifact
        uses: actions/download-artifact@v2
        with:
          name: website-dist
          path: dist
          
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist